{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/GaboGolCs/PainPredict-Neuro/blob/g3-hito6-generar-catalogo/generar_catalogo.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Hito 6 -  Actividad 1: Construcción del Catálogo de Metadatos EEG"
      ],
      "metadata": {
        "id": "0Y1YQ8TYlg4M"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install mne"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "KDLkQjK_yFH3",
        "outputId": "7d4f301e-0660-428d-dacf-cdef6bc36633",
        "collapsed": true
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: mne in /usr/local/lib/python3.12/dist-packages (1.12.1)\n",
            "Requirement already satisfied: decorator>=5.1 in /usr/local/lib/python3.12/dist-packages (from mne) (5.3.1)\n",
            "Requirement already satisfied: jinja2>=3.1 in /usr/local/lib/python3.12/dist-packages (from mne) (3.1.6)\n",
            "Requirement already satisfied: lazy-loader>=0.3 in /usr/local/lib/python3.12/dist-packages (from mne) (0.5)\n",
            "Requirement already satisfied: matplotlib>=3.8 in /usr/local/lib/python3.12/dist-packages (from mne) (3.10.0)\n",
            "Requirement already satisfied: numpy<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from mne) (2.0.2)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from mne) (26.2)\n",
            "Requirement already satisfied: pooch>=1.5 in /usr/local/lib/python3.12/dist-packages (from mne) (1.9.0)\n",
            "Requirement already satisfied: scipy>=1.13 in /usr/local/lib/python3.12/dist-packages (from mne) (1.16.3)\n",
            "Requirement already satisfied: tqdm>=4.66 in /usr/local/lib/python3.12/dist-packages (from mne) (4.67.3)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=3.1->mne) (3.0.3)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mne) (1.3.3)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mne) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mne) (4.63.0)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mne) (1.5.0)\n",
            "Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mne) (11.3.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mne) (3.3.2)\n",
            "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mne) (2.9.0.post0)\n",
            "Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.5->mne) (4.10.0)\n",
            "Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.5->mne) (2.32.4)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.8->mne) (1.17.0)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pooch>=1.5->mne) (3.4.7)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pooch>=1.5->mne) (3.18)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pooch>=1.5->mne) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pooch>=1.5->mne) (2026.6.17)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# ==============================================================================\n",
        "# Hito 6 - Actividad 1: Construcción del Catálogo de Metadatos EEG\n",
        "# Bloque de Integración Final y Pruebas (QA)\n",
        "# Integración y Control de Calidad por: Juan\n",
        "# ==============================================================================\n",
        "\n",
        "import os\n",
        "import pandas as pd\n",
        "import mne\n",
        "from google.colab import drive\n",
        "\n",
        "# 1. Conectar Colab con Google Drive\n",
        "drive.mount('/content/drive')\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# Tarea Ivonne: Exploración y Lectura de Archivos\n",
        "# ==========================================\n",
        "def explorar_archivos_tensores(ruta_base_drive):\n",
        "    \"\"\"\n",
        "    Recorre de forma recursiva la carpeta indicada en Google Drive\n",
        "    y busca todos los archivos que terminen en .fif.\n",
        "    Devuelve una lista de diccionarios con el nombre y la ruta de cada archivo.\n",
        "    \"\"\"\n",
        "    archivos_encontrados = []\n",
        "\n",
        "    # Verificamos si la ruta existe antes de empezar\n",
        "    if not os.path.exists(ruta_base_drive):\n",
        "        print(f\"Error: La ruta '{ruta_base_drive}' no existe. Revisa el nombre de la carpeta.\")\n",
        "        return archivos_encontrados\n",
        "\n",
        "    print(f\"1. Iniciando la búsqueda recursiva en: {ruta_base_drive}\")\n",
        "\n",
        "    # os.walk realiza la búsqueda recursiva de forma automática (entra a todas las subcarpetas)\n",
        "    for root, dirs, files in os.walk(ruta_base_drive):\n",
        "        for file in files:\n",
        "            # Filtramos solo los archivos con las extensiones solicitadas (.fif según pruebas reales)\n",
        "            if file.endswith('.fif'):\n",
        "                ruta_completa = os.path.join(root, file)\n",
        "\n",
        "                # Guardamos los dos datos clave solicitados\n",
        "                archivos_encontrados.append({\n",
        "                    'nombre_archivo': file,\n",
        "                    'ruta_drive': ruta_completa\n",
        "                })\n",
        "\n",
        "    print(f\"2. Búsqueda finalizada. Se encontraron {len(archivos_encontrados)} archivos de tensores.\")\n",
        "    return archivos_encontrados\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# Tarea Franco: Lógica de Extracción de Etiquetas\n",
        "# ==========================================\n",
        "def extraer_etiquetas_tensores(lista_archivos):\n",
        "    \"\"\"\n",
        "    Recibe la lista de diccionarios de Ivonne.\n",
        "    Abre los archivos .fif de forma ligera (sin cargar a RAM)\n",
        "    para extraer la etiqueta desde los eventos internos.\n",
        "    \"\"\"\n",
        "    # Regla de conversión estricta\n",
        "    MAPEO_NRS = {\n",
        "        32: 'NRS_2',\n",
        "        33: 'NRS_4',\n",
        "        34: 'NRS_6',\n",
        "        35: 'NRS_8'\n",
        "    }\n",
        "\n",
        "    datos_para_csv = []\n",
        "\n",
        "    print(f\"\\n3. Iniciando extracción desde el INTERIOR de {len(lista_archivos)} archivos .fif...\")\n",
        "\n",
        "    for item in lista_archivos:\n",
        "        ruta = item['ruta_drive']\n",
        "        nombre = item['nombre_archivo']\n",
        "\n",
        "        try:\n",
        "            # --- TRUCO DE OPTIMIZACIÓN (Cero consumo de RAM pesada) ---\n",
        "            # preload=False lee solo la cabecera y los metadatos, no los datos pesados\n",
        "            epochs = mne.read_epochs(ruta, preload=False, verbose=False)\n",
        "\n",
        "            # En los archivos .fif de épocas, la clase de dolor se guarda en los 'events'\n",
        "            # (específicamente en la tercera columna del arreglo de eventos)\n",
        "            # Tomamos la clase del primer evento de ese archivo:\n",
        "            clase_original = epochs.events[0, 2]\n",
        "\n",
        "            # --- CONVERSIÓN ESTRICTA ---\n",
        "            if clase_original in MAPEO_NRS:\n",
        "                clase_convertida = MAPEO_NRS[clase_original]\n",
        "            else:\n",
        "                clase_convertida = f'Clase_Desconocida_{clase_original}'\n",
        "\n",
        "            datos_para_csv.append({\n",
        "                'nombre_archivo': nombre,\n",
        "                'ruta_drive': ruta,\n",
        "                'nrs_clase': clase_convertida\n",
        "            })\n",
        "\n",
        "        except Exception as e:\n",
        "            # Si un archivo está corrupto, lo informamos pero no detenemos el script\n",
        "            print(f\"  [Advertencia QA] Error al leer {nombre}: {e}\")\n",
        "            datos_para_csv.append({\n",
        "                'nombre_archivo': nombre,\n",
        "                'ruta_drive': ruta,\n",
        "                'nrs_clase': 'Error_Lectura'\n",
        "            })\n",
        "\n",
        "    print(\"4. Extracción de etiquetas finalizada.\")\n",
        "    return datos_para_csv\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# Tarea Ignacio: Armado del DataFrame y CSV Final\n",
        "# ==========================================\n",
        "def construir_catalogo_csv(datos_etiquetados, nombre_salida):\n",
        "    \"\"\"\n",
        "    Recibe la lista de diccionarios generada por Franco (datos_etiquetados)\n",
        "    y construye el catálogo final en CSV con las 3 columnas exigidas:\n",
        "    nombre_archivo, ruta_drive, nrs_clase.\n",
        "    \"\"\"\n",
        "    columnas_esperadas = ['nombre_archivo', 'ruta_drive', 'nrs_clase']\n",
        "\n",
        "    df_catalogo = pd.DataFrame(datos_etiquetados)\n",
        "\n",
        "    # Verificación de integridad: forzamos exactamente estas 3 columnas y este orden,\n",
        "    # sin importar cómo vinieron los diccionarios.\n",
        "    df_catalogo = df_catalogo[columnas_esperadas]\n",
        "\n",
        "    # --- Control de calidad sobre las etiquetas ---\n",
        "    print(\"\\n\" + \"=\"*50)\n",
        "    print(\"REPORTE DE CONTROL DE CALIDAD (QA)\")\n",
        "    print(\"=\"*50)\n",
        "\n",
        "    problemas = df_catalogo[\n",
        "        df_catalogo['nrs_clase'].astype(str).str.startswith(('Error_Lectura', 'Clase_Desconocida'))\n",
        "    ]\n",
        "    if not problemas.empty:\n",
        "        print(f\"[Aviso QA] {len(problemas)} archivo(s) con etiqueta problemática:\")\n",
        "        print(problemas[['nombre_archivo', 'nrs_clase']].to_string(index=False))\n",
        "    else:\n",
        "        print(\"[OK] Todas las etiquetas se mapearon correctamente a NRS_2/NRS_4/NRS_6/NRS_8.\")\n",
        "\n",
        "    # --- Verificación de nombres de archivo duplicados ---\n",
        "    duplicados = df_catalogo[df_catalogo.duplicated(subset='nombre_archivo', keep=False)]\n",
        "    if not duplicados.empty:\n",
        "        print(f\"[Aviso QA] {len(duplicados)} nombre(s) de archivo duplicados detectados.\")\n",
        "    else:\n",
        "        print(\"[OK] No se detectaron nombres de archivo duplicados.\")\n",
        "\n",
        "    # --- Distribución de clases (chequeo rápido de balance) ---\n",
        "    print(\"\\nDistribución de clases NRS:\")\n",
        "    print(df_catalogo['nrs_clase'].value_counts())\n",
        "\n",
        "    # --- Exportación final ---\n",
        "    df_catalogo.to_csv(nombre_salida, index=False)\n",
        "    print(\"=\"*50)\n",
        "    print(f\"[+] Catálogo generado y guardado en Drive: '{nombre_salida}' con {len(df_catalogo)} filas.\")\n",
        "    print(f\"    Columnas: {list(df_catalogo.columns)}\")\n",
        "    print(\"=\"*50)\n",
        "\n",
        "    return df_catalogo\n",
        "\n",
        "\n",
        "# ==============================================================================\n",
        "# EJECUCIÓN DEL PIPELINE COMPLETO (Juan)\n",
        "# ==============================================================================\n",
        "if __name__ == \"__main__\":\n",
        "    # Ruta carpeta \"Tensores\" compartida en Drive\n",
        "    RUTA_CARPETA_TENSORES = '/content/drive/Shareddrives/DATA_GPI/Tensores'\n",
        "\n",
        "    # MODIFICACIÓN DE QA: Ruta directa a la raíz de la unidad compartida\n",
        "    RUTA_SALIDA_CSV = '/content/drive/Shareddrives/DATA_GPI/catalogo_eeg.csv'\n",
        "\n",
        "    print(\"=== EJECUTANDO FLUJO INTEGRADO DE EXTRACCIÓN Y QA ===\\n\")\n",
        "\n",
        "    # 1. Ejecutar Fase de Ivonne\n",
        "    lista_tensores = explorar_archivos_tensores(RUTA_CARPETA_TENSORES)\n",
        "\n",
        "    if lista_tensores:\n",
        "        # 2. Ejecutar Fase de Franco\n",
        "        datos_etiquetados = extraer_etiquetas_tensores(lista_tensores)\n",
        "\n",
        "        # 3. Ejecutar Fase de Ignacio (Guardando el archivo directamente en la carpeta de Drive)\n",
        "        df_final = construir_catalogo_csv(datos_etiquetados, RUTA_SALIDA_CSV)\n",
        "\n",
        "        print(\"\\n[Listo] Flujo probado de punta a punta. Catálogo generado sin caídas directamente en Drive.\")\n",
        "        # Vista previa de control final\n",
        "        print(df_final.head(5))\n",
        "    else:\n",
        "        print(\"\\n[-] Error en la integración: No se encontraron archivos para procesar.\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "pXLKqB9GyeTA",
        "outputId": "e1f7e822-41cb-47e0-c6c1-d03788073123"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n",
            "=== EJECUTANDO FLUJO INTEGRADO DE EXTRACCIÓN Y QA ===\n",
            "\n",
            "1. Iniciando la búsqueda recursiva en: /content/drive/Shareddrives/DATA_GPI/Tensores\n",
            "2. Búsqueda finalizada. Se encontraron 54 archivos de tensores.\n",
            "\n",
            "3. Iniciando extracción desde el INTERIOR de 54 archivos .fif...\n",
            "4. Extracción de etiquetas finalizada.\n",
            "\n",
            "==================================================\n",
            "REPORTE DE CONTROL DE CALIDAD (QA)\n",
            "==================================================\n",
            "[OK] Todas las etiquetas se mapearon correctamente a NRS_2/NRS_4/NRS_6/NRS_8.\n",
            "[OK] No se detectaron nombres de archivo duplicados.\n",
            "\n",
            "Distribución de clases NRS:\n",
            "nrs_clase\n",
            "NRS_4    19\n",
            "NRS_6    18\n",
            "NRS_2    17\n",
            "Name: count, dtype: int64\n",
            "==================================================\n",
            "[+] Catálogo generado y guardado en Drive: '/content/drive/Shareddrives/DATA_GPI/catalogo_eeg.csv' con 54 filas.\n",
            "    Columnas: ['nombre_archivo', 'ruta_drive', 'nrs_clase']\n",
            "==================================================\n",
            "\n",
            "[Listo] Flujo probado de punta a punta. Catálogo generado sin caídas directamente en Drive.\n",
            "                                 nombre_archivo  \\\n",
            "0   sub-045_ses-4_task-95ByBP_eeg_clean-epo.fif   \n",
            "1   sub-045_ses-1_task-95ByBP_eeg_clean-epo.fif   \n",
            "2   sub-044_ses-6_task-95ByBP_eeg_clean-epo.fif   \n",
            "3   sub-045_ses-3_task-95ByBP_eeg_clean-epo.fif   \n",
            "4   sub-045_ses-5_task-95ByBP_eeg_clean-epo.fif   \n",
            "\n",
            "                                          ruta_drive nrs_clase  \n",
            "0  /content/drive/Shareddrives/DATA_GPI/Tensores/...     NRS_6  \n",
            "1  /content/drive/Shareddrives/DATA_GPI/Tensores/...     NRS_6  \n",
            "2  /content/drive/Shareddrives/DATA_GPI/Tensores/...     NRS_2  \n",
            "3  /content/drive/Shareddrives/DATA_GPI/Tensores/...     NRS_2  \n",
            "4  /content/drive/Shareddrives/DATA_GPI/Tensores/...     NRS_4  \n"
          ]
        }
      ]
    }
  ]
}