# -*- coding: utf-8 -*-
"""sanitize_tensors.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYg-MNTk_exESg4TXvhV3FjBq8Pr7RiW
"""

import mne
import os
import gc
from google.colab import drive

# 1. LÓGICA CORE (Ivonne)
def purgar_eog_mne(ruta_origen_fif, ruta_destino_fif):
    """
    Carga un archivo .fif de un paciente, elimina los canales EOG (HEOR, VEO)
    de forma segura usando MNE y guarda el nuevo archivo.
    """
    try:
        data_mne = mne.read_epochs(ruta_origen_fif, preload=True, verbose=False)
    except ValueError:
        data_mne = mne.io.read_raw_fif(ruta_origen_fif, preload=True, verbose=False)

    canales_actuales = data_mne.ch_names
    canales_eog = ['HEOR', 'VEO']
    canales_a_borrar = [ch for ch in canales_eog if ch in canales_actuales]

    if canales_a_borrar:
        data_mne.drop_channels(canales_a_borrar)

    assert len(data_mne.ch_names) == 61, f"Error: Quedaron {len(data_mne.ch_names)} canales."

    os.makedirs(os.path.dirname(ruta_destino_fif), exist_ok=True)
    data_mne.save(ruta_destino_fif, overwrite=True, verbose=False)

# 2. MOTOR DE EJECUCIÓN (Juan)
def procesar_lote_pacientes(ruta_in, ruta_out):
    os.makedirs(ruta_out, exist_ok=True)
    archivos_fif = [f for f in os.listdir(ruta_in) if f.endswith('.fif')]

    for archivo in archivos_fif:
        ruta_origen_paciente = os.path.join(ruta_in, archivo)
        ruta_destino_paciente = os.path.join(ruta_out, archivo)

        if os.path.exists(ruta_destino_paciente):
            continue

        try:
            purgar_eog_mne(ruta_origen_paciente, ruta_destino_paciente)
        except Exception as e:
            pass
        finally:
            gc.collect()

if __name__ == "__main__":
    drive.mount('/content/drive')
    RUTA_ORIGEN = '/content/drive/Shareddrives/DATA_GPI/Tensores/'
    RUTA_DESTINO = '/content/drive/Shareddrives/DATA_GPI/tensoresSinOjos/'
    procesar_lote_pacientes(RUTA_ORIGEN, RUTA_DESTINO)